### ISSUE TITLE
What does `get_inst_x` do?

### ISSUE THREAD

**Issue by KinWaiCheuk** [biboamy/instrument-disentangle#1]
In your `v3/disentangled training/run.py`, line 41, you loaded a file named `cqt_avg_std.npy` and return the `avg` and `std`.

Later, these two variables will be used in line 19, the `get_inst_x` function of your `model.py`.
I do not understand what does this function do. Can you explain a little bit? 

Also how do you calculate the `avg` and `std` in your `cqt_avg_std.npy`? It would be nice if you can share a sample file. Now it is difficult to image what does this function do.

(To me, it just seems like normalization, but the function name is `get_inst_x`, it also seems like get instrument from x to me, that's why I would like to clarify.)

**Comment by biboamy** [comment]
Hey sorry for the bad naming and messy code. Yes, it's just a normalization. You can get the avg and std from this code: 

https://github.com/biboamy/instrument-disentangle/blob/bdf6e7d36ce36e6abe0249712cc9b853e77e7a36/v2/process.py#L232

Let me know if you have other questions.
